import Foundation

public enum HanlinSwiftUIOutputGenerator {
    public static let version = "1.0.0"

    public static func buildInventory(
        inputs: [HanlinSwiftUIInterfaceInput],
        sdkIdentity: String,
        configuration: HanlinSwiftUIBridgeConfiguration
    ) throws -> HanlinSwiftUIInventory {
        var identities: [HanlinSwiftUIInterfaceIdentity] = []
        var declarations: [HanlinSwiftUIDeclaration] = []
        for input in inputs.sorted(by: { $0.module < $1.module }) {
            let parsed = try HanlinSwiftUIInterfaceParser.parse(input)
            identities.append(parsed.identity)
            declarations.append(contentsOf: parsed.declarations)
        }
        declarations = mergeOverloads(declarations)
        declarations = HanlinSwiftUIClassifier.classify(declarations: declarations, configuration: configuration)
        return .init(
            generatorVersion: version,
            sdkIdentity: sdkIdentity,
            interfaces: identities,
            declarations: declarations
        )
    }

    public static func write(
        inventory: HanlinSwiftUIInventory,
        configuration: HanlinSwiftUIBridgeConfiguration,
        outputRoot: URL
    ) throws {
        let fileManager = FileManager.default
        try fileManager.createDirectory(at: outputRoot, withIntermediateDirectories: true)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        try appendNewline(encoder.encode(inventory)).write(to: outputRoot.appending(path: "swiftui-inventory.json"))

        let relevant = inventory.declarations.filter { $0.kind == .view || $0.kind == .modifier }
        let counts = Dictionary(grouping: relevant, by: { $0.status?.rawValue ?? "unclassified" })
            .mapValues(\.count)
        let coverage = HanlinSwiftUICoverage(
            sdkIdentity: inventory.sdkIdentity,
            generatorVersion: inventory.generatorVersion,
            bridgeVersion: configuration.bridgeVersion,
            expoUIVersion: configuration.expoUIVersion,
            interfaceHashes: Dictionary(uniqueKeysWithValues: inventory.interfaces.map { ($0.module, $0.sha256) }),
            counts: counts,
            symbols: relevant
        )
        try appendNewline(encoder.encode(coverage)).write(to: outputRoot.appending(path: "coverage.json"))
        try coverageMarkdown(coverage).write(to: outputRoot.appending(path: "coverage.md"), atomically: true, encoding: .utf8)
        try generatedSwift(inventory, configuration: configuration).write(
            to: outputRoot.appending(path: "HanlinGeneratedModifiers.swift"), atomically: true, encoding: .utf8
        )
        try generatedSwiftViews(inventory, configuration: configuration).write(
            to: outputRoot.appending(path: "HanlinGeneratedViews.swift"), atomically: true, encoding: .utf8
        )
        try generatedTypeScript(inventory).write(
            to: outputRoot.appending(path: "modifiers.ts"), atomically: true, encoding: .utf8
        )
        try generatedTypeScriptViews(inventory).write(
            to: outputRoot.appending(path: "views.tsx"), atomically: true, encoding: .utf8
        )
        try generatedManifest(inventory, configuration: configuration).write(
            to: outputRoot.appending(path: "bridge-manifest.ts"), atomically: true, encoding: .utf8
        )
    }

    private static func mergeOverloads(_ declarations: [HanlinSwiftUIDeclaration]) -> [HanlinSwiftUIDeclaration] {
        var merged: [String: HanlinSwiftUIDeclaration] = [:]
        for declaration in declarations {
            let key = "\(declaration.module)|\(declaration.kind.rawValue)|\(declaration.symbol)"
            if var existing = merged[key] {
                existing.signatures.append(contentsOf: declaration.signatures.filter { !existing.signatures.contains($0) })
                existing.availability = Array(Set(existing.availability + declaration.availability)).sorted()
                existing.enumCases = Array(Set(existing.enumCases + declaration.enumCases)).sorted()
                merged[key] = existing
            } else {
                merged[key] = declaration
            }
        }
        return merged.values.sorted { ($0.module, $0.symbol, $0.kind.rawValue) < ($1.module, $1.symbol, $1.kind.rawValue) }
    }

    private static func coverageMarkdown(_ coverage: HanlinSwiftUICoverage) -> String {
        var lines = [
            "<!-- Generated by hanlin-swiftui-bridge. Do not edit. -->",
            "# Hanlin SwiftUI bridge coverage",
            "",
            "- SDK/toolchain identity: `\(coverage.sdkIdentity)`",
            "- Generator: `\(coverage.generatorVersion)`",
            "- Bridge: `\(coverage.bridgeVersion)`",
            "- Expo UI: `\(coverage.expoUIVersion)`",
            "",
            "| Classification | Count |",
            "| --- | ---: |",
        ]
        for status in HanlinSwiftUIBridgeStatus.allCases {
            lines.append("| \(status.rawValue) | \(coverage.counts[status.rawValue, default: 0]) |")
        }
        lines.append(contentsOf: ["", "## Symbols", "", "| Module | Symbol | Kind | Tier | Status | Reason |", "| --- | --- | --- | --- | --- | --- |"])
        for symbol in coverage.symbols {
            let reason = (symbol.reason ?? "").replacingOccurrences(of: "|", with: "\\|")
            lines.append("| \(symbol.module) | `\(symbol.symbol)` | \(symbol.kind.rawValue) | \(symbol.tier?.rawValue ?? "-") | \(symbol.status?.rawValue ?? "-") | \(reason) |")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private static func generatedSwift(
        _ inventory: HanlinSwiftUIInventory,
        configuration: HanlinSwiftUIBridgeConfiguration
    ) -> String {
        let modifiers = inventory.declarations.filter {
            $0.kind == .modifier && $0.status == .generated && !configuration.expoModifiers.contains($0.symbol)
        }
        var lines = [
            "// Generated by hanlin-swiftui-bridge \(version). Do not edit.",
            "import ExpoModulesCore",
            "import ExpoUI",
            "import SwiftUI",
            "",
        ]
        let enumDeclarations = Dictionary(uniqueKeysWithValues: inventory.declarations
            .filter { !$0.enumCases.isEmpty }
            .map { ($0.symbol, $0) })
        let usedEnums = Set(modifiers.flatMap { modifier in
            modifier.signatures.flatMap(\.parameters).compactMap { parameter in
                enumDeclarations[parameter.type]?.symbol
            }
        })
        for enumName in usedEnums.sorted() {
            guard let declaration = enumDeclarations[enumName] else { continue }
            let bridgeType = generatedEnumType(enumName)
            lines.append("public enum \(bridgeType): String, Enumerable {")
            for enumCase in declaration.enumCases.sorted() {
                lines.append("    case \(enumCase)")
            }
            lines.append("")
            lines.append("    var swiftUIValue: \(enumName) {")
            lines.append("        switch self {")
            for enumCase in declaration.enumCases.sorted() {
                lines.append("        case .\(enumCase): .\(enumCase)")
            }
            lines.append("        }")
            lines.append("    }")
            lines.append("}")
            lines.append("")
        }
        for modifier in modifiers {
            guard let signature = modifier.signatures.first(where: { signature in
                !signature.parameters.contains(where: { $0.isBinding || ($0.isClosure && !$0.isViewBuilder) })
            }), !signature.parameters.contains(where: \.isViewBuilder) else { continue }
            let typeName = "HanlinGenerated\(upperCamel(modifier.symbol))Modifier"
            lines.append("public struct \(typeName): ViewModifier, Record {")
            for parameter in signature.parameters {
                lines.append("    @Field public var \(parameter.localName): \(fieldType(parameter.type, enums: enumDeclarations)) = \(fieldDefault(parameter, enums: enumDeclarations))")
            }
            lines.append("")
            lines.append("    public init() {}")
            lines.append("")
            lines.append("    public func body(content: Content) -> some View {")
            let arguments = signature.parameters.map { parameter in
                let value = nativeValue(parameter, enums: enumDeclarations)
                return parameter.externalName.map { "\($0): \(value)" } ?? value
            }.joined(separator: ", ")
            lines.append("        content.\(modifier.symbol)(\(arguments))")
            lines.append("    }")
            lines.append("}")
            lines.append("")
        }
        lines.append("public enum HanlinGeneratedModifierRegistry {")
        lines.append("    @MainActor public static func register() {")
        for modifier in modifiers {
            let typeName = "HanlinGenerated\(upperCamel(modifier.symbol))Modifier"
            lines.append("        ViewModifierRegistry.register(\"\(modifier.symbol)\") { params, appContext, _ in")
            lines.append("            try \(typeName)(from: params, appContext: appContext)")
            lines.append("        }")
        }
        lines.append("    }")
        lines.append("")
        lines.append("    public static func unregister() {")
        for modifier in modifiers {
            lines.append("        ViewModifierRegistry.unregister(\"\(modifier.symbol)\")")
        }
        lines.append("    }")
        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }

    private static func generatedTypeScript(_ inventory: HanlinSwiftUIInventory) -> String {
        let modifiers = inventory.declarations.filter { $0.kind == .modifier && $0.status == .generated }
        var lines = [
            "// Generated by hanlin-swiftui-bridge \(version). Do not edit.",
            "import { createModifier, type ModifierConfig } from '@expo/ui/swift-ui/modifiers';",
            "",
        ]
        for modifier in modifiers {
            guard let signature = modifier.signatures.first(where: { !$0.parameters.contains(where: { $0.isClosure || $0.isBinding }) }) else { continue }
            let parameters = signature.parameters.map { parameter in
                let optional = parameter.defaultValue == nil ? "" : "?"
                return "\(parameter.localName)\(optional): \(typescriptType(parameter.type, inventory: inventory))"
            }.joined(separator: ", ")
            let object = signature.parameters.map { "\($0.localName): \($0.localName)" }.joined(separator: ", ")
            lines.append("export const \(modifier.symbol) = (\(parameters)): ModifierConfig =>")
            lines.append("  createModifier('\(modifier.symbol)', { \(object) });")
            lines.append("")
        }
        return lines.joined(separator: "\n")
    }

    private static func generatedSwiftViews(
        _ inventory: HanlinSwiftUIInventory,
        configuration: HanlinSwiftUIBridgeConfiguration
    ) -> String {
        let views = inventory.declarations.filter { $0.kind == .view && $0.status == .generated }
        let enumDeclarations = Dictionary(uniqueKeysWithValues: inventory.declarations
            .filter { !$0.enumCases.isEmpty }
            .map { ($0.symbol, $0) })
        var lines = [
            "// Generated by hanlin-swiftui-bridge \(version). Do not edit.",
            "import ExpoModulesCore",
            "import ExpoUI",
            "import SwiftUI",
            "",
        ]
        let usedEnums = Set(views.flatMap { view in
            selectedViewSignature(view)?.parameters.compactMap { parameter in
                enumDeclaration(for: parameter.type, enums: enumDeclarations)?.symbol
            } ?? []
        })
        for enumName in usedEnums.sorted() {
            guard let declaration = enumDeclarations[enumName] else { continue }
            let bridgeType = generatedViewEnumType(enumName)
            lines.append("public enum \(bridgeType): String, Enumerable {")
            for enumCase in declaration.enumCases.sorted() { lines.append("    case \(enumCase)") }
            lines.append("")
            lines.append("    var swiftUIValue: \(enumName) {")
            lines.append("        switch self {")
            for enumCase in declaration.enumCases.sorted() { lines.append("        case .\(enumCase): .\(enumCase)") }
            lines.append("        }")
            lines.append("    }")
            lines.append("}")
            lines.append("")
        }
        for view in views {
            guard let signature = selectedViewSignature(view) else { continue }
            let baseName = upperCamel(view.symbol)
            let propsName = "HanlinGenerated\(baseName)Props"
            let viewName = "HanlinGenerated\(baseName)View"
            let valueParameters = signature.parameters.filter { !$0.isViewBuilder }
            lines.append("public final class \(propsName): UIBaseViewProps {")
            for parameter in valueParameters {
                lines.append("    @Field public var \(parameter.localName): \(viewFieldType(parameter.type, enums: enumDeclarations)) = \(viewFieldDefault(parameter, enums: enumDeclarations))")
            }
            lines.append("}")
            lines.append("")
            lines.append("public struct \(viewName): ExpoSwiftUI.View {")
            lines.append("    @ObservedObject public var props: \(propsName)")
            lines.append("")
            lines.append("    public var body: some View {")
            let arguments = valueParameters.map { parameter in
                let value = viewNativeValue(parameter, enums: enumDeclarations)
                return parameter.externalName.map { "\($0): \(value)" } ?? value
            }.joined(separator: ", ")
            if signature.parameters.last?.isViewBuilder == true {
                lines.append("        SwiftUI.\(view.symbol)(\(arguments)) {")
                lines.append("            Children()")
                lines.append("        }")
            } else {
                lines.append("        SwiftUI.\(view.symbol)(\(arguments))")
            }
            lines.append("    }")
            lines.append("}")
            lines.append("")
        }
        lines.append("public enum HanlinGeneratedBridgeMetadata {")
        lines.append("    public static let runtimeVersion = \"\(configuration.runtimeVersion)\"")
        lines.append("    public static let bridgeVersion = \"\(configuration.bridgeVersion)\"")
        lines.append("    public static let inventoryIdentity = \"\(inventory.sdkIdentity)\"")
        lines.append("}")
        lines.append("")
        lines.append("public final class HanlinGeneratedExpoUIModule: Module {")
        lines.append("    public func definition() -> ModuleDefinition {")
        lines.append("        Name(\"HanlinGeneratedExpoUI\")")
        for view in views {
            lines.append("        ExpoUIView(HanlinGenerated\(upperCamel(view.symbol))View.self)")
        }
        lines.append("    }")
        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }

    private static func generatedTypeScriptViews(_ inventory: HanlinSwiftUIInventory) -> String {
        let views = inventory.declarations.filter { $0.kind == .view && $0.status == .generated }
        var lines = [
            "// Generated by hanlin-swiftui-bridge \(version). Do not edit.",
            "import React from 'react';",
            "import { requireNativeView } from 'expo';",
            "import type { CommonViewModifierProps } from '@expo/ui/swift-ui';",
            "import { createViewModifierEventListener } from '@expo/ui/swift-ui/modifiers';",
            "",
        ]
        for view in views {
            guard let signature = selectedViewSignature(view) else { continue }
            let name = upperCamel(view.symbol)
            let values = signature.parameters.filter { !$0.isViewBuilder }
            lines.append("export interface \(name)Props extends CommonViewModifierProps {")
            for parameter in values {
                let optional = parameter.defaultValue == nil ? "" : "?"
                lines.append("  \(parameter.localName)\(optional): \(typescriptType(parameter.type, inventory: inventory));")
            }
            if signature.parameters.contains(where: \.isViewBuilder) { lines.append("  children?: React.ReactNode;") }
            lines.append("}")
            lines.append("")
            lines.append("const Native\(name) = requireNativeView<\(name)Props>('HanlinGeneratedExpoUI', 'HanlinGenerated\(name)View');")
            lines.append("")
            lines.append("export function \(name)({ modifiers, ...props }: \(name)Props) {")
            lines.append("  return (")
            lines.append("    <Native\(name)")
            lines.append("      {...props}")
            lines.append("      modifiers={modifiers}")
            lines.append("      {...(modifiers ? createViewModifierEventListener(modifiers) : undefined)}")
            lines.append("    />")
            lines.append("  );")
            lines.append("}")
            lines.append("")
        }
        return lines.joined(separator: "\n")
    }

    private static func generatedManifest(
        _ inventory: HanlinSwiftUIInventory,
        configuration: HanlinSwiftUIBridgeConfiguration
    ) -> String {
        let relevant = inventory.declarations.filter { $0.kind == .view || $0.kind == .modifier }
        let symbols = relevant
            .filter { [.expoUpstream, .generated, .manual].contains($0.status) }
            .map(\.symbol)
            .sorted()
            .map { "  '\($0)'," }
            .joined(separator: "\n")
        let classifications = relevant
            .map { "  '\($0.symbol)': '\($0.status?.rawValue ?? "unclassified")'," }
            .joined(separator: "\n")
        return """
        // Generated by hanlin-swiftui-bridge \(version). Do not edit.
        export const HANLIN_EXPO_RUNTIME_VERSION = '\(configuration.runtimeVersion)' as const;
        export const HANLIN_EXPO_UI_BRIDGE_VERSION = '\(configuration.bridgeVersion)' as const;
        export const HANLIN_SWIFTUI_SDK_IDENTITY = '\(inventory.sdkIdentity)' as const;
        export const HANLIN_SWIFTUI_SYMBOLS = [
        \(symbols)
        ] as const;
        export type HanlinSwiftUISymbol = (typeof HANLIN_SWIFTUI_SYMBOLS)[number];
        export const HANLIN_SWIFTUI_CLASSIFICATIONS = {
        \(classifications)
        } as const;
        """ + "\n"
    }

    private static func fieldType(_ type: String, enums: [String: HanlinSwiftUIDeclaration]) -> String {
        let normalized = type.replacingOccurrences(of: "Swift.", with: "")
        if enums[normalized] != nil { return generatedEnumType(normalized) }
        return normalized
    }

    private static func fieldDefault(
        _ parameter: HanlinSwiftUIParameter,
        enums: [String: HanlinSwiftUIDeclaration]
    ) -> String {
        if parameter.defaultValue == nil && parameter.type.trimmingCharacters(in: .whitespaces).hasSuffix("?") {
            return "nil"
        }
        if let declaration = enumDeclaration(for: parameter.type, enums: enums) {
            return parameter.defaultValue ?? declaration.enumCases.sorted().first.map { ".\($0)" } ?? ".automatic"
        }
        if let value = parameter.defaultValue { return value }
        let type = parameter.type.replacingOccurrences(of: "Swift.", with: "")
        if type.contains("Bool") { return "false" }
        if type.contains("String") { return "\"\"" }
        return "0"
    }

    private static func nativeValue(
        _ parameter: HanlinSwiftUIParameter,
        enums: [String: HanlinSwiftUIDeclaration]
    ) -> String {
        guard enumDeclaration(for: parameter.type, enums: enums) != nil else { return parameter.localName }
        return parameter.type.trimmingCharacters(in: .whitespaces).hasSuffix("?")
            ? "\(parameter.localName)?.swiftUIValue"
            : "\(parameter.localName).swiftUIValue"
    }

    private static func typescriptType(_ type: String, inventory: HanlinSwiftUIInventory) -> String {
        let normalized = type.replacingOccurrences(of: "Swift.", with: "").replacingOccurrences(of: "?", with: "")
        if ["Bool"].contains(normalized) { return "boolean" }
        if ["Int", "Int32", "Int64", "Double", "Float", "CGFloat"].contains(normalized) { return "number" }
        if normalized == "String" { return "string" }
        if let enumDeclaration = inventory.declarations.first(where: {
            !$0.enumCases.isEmpty && ($0.symbol == normalized || normalized.hasSuffix($0.symbol))
        }) {
            return enumDeclaration.enumCases.map { "'\($0)'" }.joined(separator: " | ")
        }
        return "never"
    }

    private static func upperCamel(_ value: String) -> String {
        guard let first = value.first else { return value }
        return first.uppercased() + value.dropFirst()
    }

    private static func generatedEnumType(_ value: String) -> String {
        "HanlinGenerated" + value.split(separator: ".").map { upperCamel(String($0)) }.joined() + "Value"
    }

    private static func selectedViewSignature(_ declaration: HanlinSwiftUIDeclaration) -> HanlinSwiftUISignature? {
        declaration.signatures.first { signature in
            let builders = signature.parameters.filter(\.isViewBuilder)
            return !signature.isAsync
                && !signature.isThrowing
                && builders.count <= 1
                && builders.allSatisfy { $0.type.replacingOccurrences(of: " ", with: "").hasPrefix("()->") }
                && (builders.isEmpty || signature.parameters.last?.isViewBuilder == true)
                && signature.parameters.allSatisfy { !$0.isBinding && (!$0.isClosure || $0.isViewBuilder) }
        }
    }

    private static func enumDeclaration(
        for type: String,
        enums: [String: HanlinSwiftUIDeclaration]
    ) -> HanlinSwiftUIDeclaration? {
        let normalized = type
            .replacingOccurrences(of: "Swift.", with: "")
            .replacingOccurrences(of: "?", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        if let exact = enums[normalized] { return exact }
        guard let key = enums.keys.sorted().first(where: { normalized.hasSuffix($0) }) else { return nil }
        return enums[key]
    }

    private static func viewFieldType(_ type: String, enums: [String: HanlinSwiftUIDeclaration]) -> String {
        guard let declaration = enumDeclaration(for: type, enums: enums) else {
            return type.replacingOccurrences(of: "Swift.", with: "")
        }
        let optional = type.trimmingCharacters(in: .whitespaces).hasSuffix("?") ? "?" : ""
        return generatedViewEnumType(declaration.symbol) + optional
    }

    private static func viewFieldDefault(
        _ parameter: HanlinSwiftUIParameter,
        enums: [String: HanlinSwiftUIDeclaration]
    ) -> String {
        if parameter.defaultValue == nil && parameter.type.trimmingCharacters(in: .whitespaces).hasSuffix("?") {
            return "nil"
        }
        if let declaration = enumDeclaration(for: parameter.type, enums: enums) {
            return parameter.defaultValue ?? declaration.enumCases.sorted().first.map { ".\($0)" } ?? ".automatic"
        }
        return fieldDefault(parameter, enums: enums)
    }

    private static func viewNativeValue(
        _ parameter: HanlinSwiftUIParameter,
        enums: [String: HanlinSwiftUIDeclaration]
    ) -> String {
        guard enumDeclaration(for: parameter.type, enums: enums) != nil else { return "props.\(parameter.localName)" }
        return parameter.type.trimmingCharacters(in: .whitespaces).hasSuffix("?")
            ? "props.\(parameter.localName)?.swiftUIValue"
            : "props.\(parameter.localName).swiftUIValue"
    }

    private static func generatedViewEnumType(_ value: String) -> String {
        "HanlinGeneratedView" + value.split(separator: ".").map { upperCamel(String($0)) }.joined() + "Value"
    }

    private static func appendNewline(_ data: Data) -> Data {
        var result = data
        result.append(0x0A)
        return result
    }
}
