import HanlinScriptingApplicationRuntime

typealias HanlinScriptingApplicationSession = HanlinScriptingApplicationRuntime.HanlinScriptingApplicationSession
typealias HanlinScriptingFetchRequest = HanlinScriptingApplicationRuntime.HanlinScriptingFetchRequest
typealias HanlinScriptingFetchResponse = HanlinScriptingApplicationRuntime.HanlinScriptingFetchResponse
typealias HanlinScriptingNetworkLoader = HanlinScriptingApplicationRuntime.HanlinScriptingNetworkLoader
typealias HanlinScriptingLocationRequest = HanlinScriptingApplicationRuntime.HanlinScriptingLocationRequest
typealias HanlinScriptingLocationInfo = HanlinScriptingApplicationRuntime.HanlinScriptingLocationInfo
typealias HanlinScriptingLocationPlacemark = HanlinScriptingApplicationRuntime.HanlinScriptingLocationPlacemark
typealias HanlinScriptingLocationResult = HanlinScriptingApplicationRuntime.HanlinScriptingLocationResult
typealias HanlinScriptingLocationLoader = HanlinScriptingApplicationRuntime.HanlinScriptingLocationLoader
typealias HanlinScriptingAssistantRequest = HanlinScriptingApplicationRuntime.HanlinScriptingAssistantRequest
typealias HanlinScriptingAssistantProvider = HanlinScriptingApplicationRuntime.HanlinScriptingAssistantProvider
typealias HanlinScriptingAssistantChunk = HanlinScriptingApplicationRuntime.HanlinScriptingAssistantChunk
typealias HanlinScriptingAssistantUsage = HanlinScriptingApplicationRuntime.HanlinScriptingAssistantUsage
typealias HanlinScriptingAssistantLoader = HanlinScriptingApplicationRuntime.HanlinScriptingAssistantLoader
typealias HanlinScriptingLiveActivityRequest = HanlinScriptingApplicationRuntime.HanlinScriptingLiveActivityRequest
typealias HanlinScriptingLiveActivityResult = HanlinScriptingApplicationRuntime.HanlinScriptingLiveActivityResult
typealias HanlinScriptingLiveActivityLoader = HanlinScriptingApplicationRuntime.HanlinScriptingLiveActivityLoader
