import HanlinScriptingApplicationRuntime

typealias HanlinScriptingApplicationSession = HanlinScriptingApplicationRuntime.HanlinScriptingApplicationSession
typealias HanlinScriptingFetchRequest = HanlinScriptingApplicationRuntime.HanlinScriptingFetchRequest
typealias HanlinScriptingFetchResponse = HanlinScriptingApplicationRuntime.HanlinScriptingFetchResponse
typealias HanlinScriptingNetworkLoader = HanlinScriptingApplicationRuntime.HanlinScriptingNetworkLoader
